import {
  Text,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalCloseButton,
  ModalHeader,
  ModalBody,
  ModalFooter,
  Button,
  Box,
  UnorderedList,
  ListItem,
  useColorModeValue,
} from '@chakra-ui/react'
import { WarningTwoIcon } from '@chakra-ui/icons'
import ScopedCSSPortal from './ScopedCSSPortal'
import Logo from './Logo'

const RarityDisclaimer = ({ onClose }: { onClose: () => void }) => {
  return (
    <ScopedCSSPortal>
      <Modal
        isOpen
        onClose={onClose}
        closeOnOverlayClick={false}
        closeOnEsc={false}
      >
        <ModalOverlay />
        <ModalContent maxWidth="container.sm">
          <ModalCloseButton />
          <ModalHeader>
            <WarningTwoIcon
              mr="1"
              mt="-1px"
              color={useColorModeValue('orange.400', 'orange.300')}
            />{' '}
            SuperSea Rarity Disclaimer
          </ModalHeader>
          <ModalBody pb="3" lineHeight="1.6em">
            <Text>
              Our rarity ranks are generated by a standardized scoring algorithm
              based purely on the traits in the NFTs metadata. Please understand
              that our reported rank could be inaccurate for a number of
              reasons:
            </Text>
            <UnorderedList
              py="4"
              css={{ '> li': { listStyleType: 'disc', pb: '0.5em' } }}
            >
              <ListItem>There's a bug in our code.</ListItem>
              <ListItem>
                The collection has been ranked before all metadata was revealed.
              </ListItem>
              <ListItem>
                The collection had its metadata updated after we ranked it.
              </ListItem>
              <ListItem>
                The community does not consider a standardized scoring algorithm
                based on combined trait rarity to be an accurate representation
                of what is a sought-after item in the given collection.
              </ListItem>
            </UnorderedList>
            <Text>
              Never make a purchasing decision based on our reported rank alone,
              always do your own due diligence. We recommend you to use the
              score breakdown, accessed by clicking the rank text, to judge if
              we've produced a reasonable rank based on the traits.
            </Text>
            <Box pt="3">
              <Logo mb="-64px" width="80px" height="80px" opacity="0.5" />
            </Box>
          </ModalBody>
          <ModalFooter>
            <Button onClick={onClose}>I understand</Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </ScopedCSSPortal>
  )
}

export default RarityDisclaimer
